### ISSUE TITLE
Server Information [Command]

### ISSUE THREAD

**Issue by danielsolartech** [sflynlang/sflynlang-bot#3]
If you knows only the basic about Discord bots, you can contribute doing a command to view the server information:

The only thing that is required: Make it in a Message Embed.

## Resources
* [Message Embed (Discord.js Guide)](https://discordjs.guide/popular-topics/embeds.html)
* [Message Embed (Discord.js Official Guide)](https://discord.js.org/#/docs/main/stable/examples/embed)

* [Server Information Command (Discord.JS Guilde)](https://discordjs.guide/creating-your-bot/adding-more-commands.html#server-info-command)
* [Guild Information (Discord.js Official Guide)](https://discord.js.org/#/docs/main/stable/class/Guild)

## Information
* Members count.
* Members banned count.
* Channels count.
* Server creation.
* Server icon.

**Comment by cfanoulis** [comment]
Hey! I'd like to claim this as well.

**Comment by danielsolartech** [comment]
@cfanoulis ready too :), keep coding!
