### ISSUE TITLE
Avatar Preview [Command]

### ISSUE THREAD

**Issue by danielsolartech** [sflynlang/sflynlang-bot#4]
If you knows only the basic about Discord bots, you can contribute doing a command to view your avatar.

The only thing thaat is required: Make it in a Message Embed.

## Resources
* [Message Embed (Discord.js Guide)](https://discordjs.guide/popular-topics/embeds.html)
* [Message Embed (Discord.js Official Guide)](https://discord.js.org/#/docs/main/stable/examples/embed)

* [Avatars Command (Discord.js Official Guide)](https://discord.js.org/#/docs/main/stable/examples/avatars)

## Information
* Username
* Avatar Preview

**Comment by cfanoulis** [comment]
Hello! I'd like to claim this early

**Comment by danielsolartech** [comment]
@cfanoulis Ready :D, happy hacktoberfest!
