### ISSUE TITLE
Syntax or orthographic corrections [EN]

### ISSUE THREAD

**Issue by danielsolartech** [sflynlang/sflynlang-bot#5]
I'm not a native english speaker and i can get mistakes in any moment, so if you find one in the documentation of the repository you can send a pull request changing it to a best way.

**Comment by hanyangl** [comment]
@danielsolartech I'm a native English speaker, which repo(s) documentation would you like me to review? I could take a look.

**Comment by danielsolartech** [comment]
Hi @hanyangl, you can review this repository (CONTRIBUTING.md, CODE_OF_CONDUCT.md, README.md).

If you want, can take a look to sflynlang/compiler repo [wiki](https://github.com/sflynlang/compiler/wiki) as well, and the same files (CONTRIBUTING.md, CODE_OF_CONDUCT.md, README.md).

**Comment by hanyangl** [comment]
All right, you can assign to me

**Comment by danielsolartech** [comment]
@hanyangl Ready, and thank you 💙

**Comment by hanyangl** [comment]
@danielsolartech I don't have permissions to push my branch to your remote. Could you give me the necessary permissions to make a PR?

**Comment by hanyangl** [comment]
<img width="603" alt="Screenshot 2020-09-26 at 10 44 23 AM" src="https://user-images.githubusercontent.com/51980145/94328450-3f21e100-ffe5-11ea-94dd-06da0d68a1c7.png">

**Comment by danielsolartech** [comment]
@hanyangl i invited you to join to the organization as a writer, you need to create a new branch and push to it and make a pull request to main branch

**Comment by hanyangl** [comment]
haha it's ok, I decided to follow the steps in your contributing doc and submit a PR from my forked repo of yours.

**Comment by hanyangl** [comment]
https://github.com/sflynlang/sflynlang-bot/pull/6

**Comment by danielsolartech** [comment]
@hanyangl Ohh, okay, i will review it :D
